### ISSUE TITLE
The latest code compilation error, can not find the relevant header file.

### ISSUE THREAD

**Issue by ouyangkan** [espressif/qemu#21]
I want to build qEMu with esp32 support and follow the instructions in readMe:  
mkdir build  
cd build  
.  /configure  
make  
Missing header file displayed during compilation,  

![image](https://user-images.githubusercontent.com/42034507/132649079-ded9f9df-07b2-47c7-8bd4-b865be0f7451.png)

Excuse me how should I solve this problem, be to lack what to rely on.

**Comment by ouyangkan** [comment]
I used ubuntu18.04。

**Comment by ouyangkan** [comment]
First, I modified subprojects\libvhost-user\libvhost-user.h and subprojects\libvhost-user\include\atomic.h. 

Content as follows:
`#include "../../include/standard-headers/linux/virtio_ring.h"`
`#include "../../../include/qemu/atomic.h"`

**Comment by igrr** [comment]
Please check https://github.com/espressif/qemu/wiki#configure, you need to pass `--enable-gcrypt` option to the configure script.

**Comment by ouyangkan** [comment]
Thank you for your reply. Now my problem has been solved.
