### ISSUE TITLE
Incorrect option syntax for PSRAM in Wiki page

### ISSUE THREAD

**Issue by smuehlst** [espressif/qemu#29]
I did not find a way to create a pull request for the Wiki page, therefore I'm creating an issue.

See here: https://github.com/espressif/qemu/wiki#adding-psram

> You can add 2MB or 4MB PSRAM using `-m 2MB` or `-m 4MB` command line options, respectively.

When I try to use this syntax it is rejected with the following error message:

```
qemu-system-xtensa: -m 2MB: Parameter 'size' expects a non-negative number below 2^64
Optional suffix k, M, G, T, P or E means kilo-, mega-, giga-, tera-, peta-
and exabytes, respectively.
```

Thefore the correct syntax is `-m 2M` or `-m 4M`.

**Comment by igrr** [comment]
Thank you for noticing this! I have updated the wiki.
