### ISSUE TITLE
WIFI-Scan example

### ISSUE THREAD

**Issue by MaxCamillo** [espressif/qemu#3]
I tried to execute the 'scan' example from the idf package. It gets stucked at:

`.check_dport_access_end () at /home/max/esp-idf/components/esp32/./dport_panic_highint_hdl.S:181`

With output message: 

`I (1044) wifi: wifi firmware version: b3258e0`
`I (1044) wifi: config NVS flash: enabled`
`I (1044) wifi: config nano formating: disabled`
`I (1054) system_api: Base MAC address is not set, read default base MAC address from BLK0 of EFUSE`
`I (1064) system_api: Base MAC address is not set, read default base MAC address from BLK0 of EFUSE`
`D (1084) nvs: nvs_open_from_partition nvs.net80211 1`

Funny thing is, that that it doesn't stuck always at the same point, but always during nvs_set or nvs_get. Do we have a racecondition here?
Is wifi code already working in this qemu port?

Best regards

**Comment by igrr** [comment]
No, Wi-Fi is not emulated, and there is no plan at the moment to add emulation of the Wi-Fi hardware. For testing network (TCP/IP) functionality you can try using Ethernet instead, which is emulated.
