### ISSUE TITLE
Unable to build on Windows 10 64bit using MSYS2 (QEMU-59)

### ISSUE THREAD

**Issue by krimoz** [espressif/qemu#53]
Following the guide on [](https://wiki.qemu.org/Hosts/W32)  (section 1.2.2	Native builds with MSYS2) :

 Installed [msys2-x86_64-20220904.exe](https://github.com/msys2/msys2-installer/releases/download/2022-09-04/msys2-x86_64-20220904.exe).
 Opened mingw64.exe as Administrator and ran the following commands.
pacman -Syu
pacman -Su
pacman -S base-devel mingw-w64-x86_64-toolchain git python ninja
pacman -S mingw-w64-x86_64-glib2 mingw-w64-x86_64-pixman python-setuptools
pacman -S mingw-w64-x86_64-gtk3 mingw-w64-x86_64-SDL2
pacman -S mingw-w64-x86_64-libgcrypt
git clone https://www.gitlab.com/qemu/qemu
cd qemu
./configure --target-list=xtensa-softmmu     --enable-gcrypt     --enable-debug --enable-sanitizers     --disable-strip --disable-user     --disable-capstone --disable-vnc     --disable-sdl --disable-gtk
ninja -C build
Got the following error : 

[331/1601] Compiling C++ object qga/vss-win32/qga-vss.dll.p/requester.cpp.obj
FAILED: qga/vss-win32/qga-vss.dll.p/requester.cpp.obj
"c++" "-m64" "-mcx16" "-Iqga/vss-win32/qga-vss.dll.p" "-Iqga/vss-win32" "-I../qga/vss-win32" "-ID:/ESP/msys64/mingw64/include" "-ID:/ESP/msys64/mingw64/include/glib-2.0" "-ID:/ESP/msys64/mingw64/lib/glib-2.0/include" "-fdiagnostics-color=auto" "-Wall" "-Winvalid-pch" "-Wnon-virtual-dtor" "-Werror" "-std=gnu++11" "-g" "-iquote" "." "-iquote" "D:/ESP/msys64/home/karim/qemu-esp" "-iquote" "D:/ESP/msys64/home/karim/qemu-esp/include" "-iquote" "D:/ESP/msys64/home/karim/qemu-esp/disas/libvixl" "-iquote" "D:/ESP/msys64/home/karim/qemu-esp/tcg/i386" "-D__STDC_LIMIT_MACROS" "-D__STDC_CONSTANT_MACROS" "-D__STDC_FORMAT_MACROS" "-D_GNU_SOURCE" "-D_FILE_OFFSET_BITS=64" "-D_LARGEFILE_SOURCE" "-Wundef" "-Wwrite-strings" "-fno-strict-aliasing" "-fno-common" "-fwrapv" "-Wtype-limits" "-Wformat-security" "-Wformat-y2k" "-Winit-self" "-Wignored-qualifiers" "-Wempty-body" "-Wendif-labels" "-Wexpansion-to-defined" "-Wimplicit-fallthrough=2" "-Wno-missing-include-dirs" "-Wno-shift-negative-value" "-Wno-psabi" "-fstack-protector-strong" "-Wno-unknown-pragmas" "-Wno-delete-non-virtual-dtor" "-Wno-non-virtual-dtor" -MD -MQ qga/vss-win32/qga-vss.dll.p/requester.cpp.obj -MF "qga/vss-win32/qga-vss.dll.p/requester.cpp.obj.d" -o qga/vss-win32/qga-vss.dll.p/requester.cpp.obj "-c" ../qga/vss-win32/requester.cpp
../qga/vss-win32/requester.cpp: In function 'void requester_freeze(int*, void*, ErrorSet*)':
../qga/vss-win32/requester.cpp:357:24: error: 'void operator delete(void*)' called on pointer returned from a mismatched allocation function [-Werror=mismatched-new-delete]
  357 |                 delete volume_name_wchar;
      |                        ^~~~~~~~~~~~~~~~~
../qga/vss-win32/requester.cpp:348:48: note: returned from 'void* operator new [](long long unsigned int)'
  348 |             volume_name_wchar = new wchar_t[len];
      |                                                ^
../qga/vss-win32/requester.cpp:362:20: error: 'void operator delete(void*)' called on pointer returned from a mismatched allocation function [-Werror=mismatched-new-delete]
  362 |             delete volume_name_wchar;
      |                    ^~~~~~~~~~~~~~~~~
../qga/vss-win32/requester.cpp:348:48: note: returned from 'void* operator new [](long long unsigned int)'
  348 |             volume_name_wchar = new wchar_t[len];
      |                                                ^

By the way I was able to use this setup to build [qemu](https://www.gitlab.com/qemu/qemu).

**Comment by igrr** [comment]
@krimoz Are you able to build the upstream qemu version? If you get the same error with the upstream version, please report the issue upstream instead. The errors don't seem to be related to ESP-specific changes.

**Comment by krimoz** [comment]
Yes ,I was able to clone and build https://www.gitlab.com/qemu/qemu.

**Comment by igrr** [comment]
That's interesting! It seems that you are using different argument list to the `./configure` script when building the upstream version.

For ESP fork you are using the following arguments:
```
./configure --target-list=xtensa-softmmu --enable-gcrypt --enable-debug --enable-sanitizers --disable-strip --disable-user --disable-capstone --disable-vnc --disable-sdl --disable-gtk
```

Could you please try to build the upstream with the same arguments?

**Comment by krimoz** [comment]
Okay, I deleted the build folder from the upstream version, then ran 
 ```
./configure --target-list=xtensa-softmmu --enable-gcrypt --enable-debug --enable-sanitizers --disable-strip --disable-user --disable-capstone --disable-vnc --disable-sdl --disable-gtk
ninja -C build
```
the ninja command completed with this :
```
ninja: Entering directory `build'
[1571/1571] Linking target tests/unit/test-yank.exe
```
