### ISSUE TITLE
release assets esp-develop-20220919 (QEMU-62)

### ISSUE THREAD

**Issue by NikLeberg** [espressif/qemu#54]
Hi @igrr 
Thanks for the update and rebase.
Do you plan to add the usual additional asset (.tar.bz2) with the prebuild qemu system to the [esp-develop-20220919](https://github.com/espressif/qemu/releases/tag/esp-develop-20220919) release?
The previous releases had those.
Thanks
Nik

**Comment by igrr** [comment]
Hi @NikLeberg, thanks for noticing this. [The release](https://github.com/espressif/qemu/releases/tag/esp-develop-20220919) has been updated, the asset is now included.
