### ISSUE TITLE
ESP32-C3 support (QEMU-93)

### ISSUE THREAD

**Issue by ozanoner** [espressif/qemu#59]
It would be great to test ESP32-C3 behaviour on qemu (especially eFuse). Thanks.

**Comment by cederom** [comment]
+1 :-)

**Comment by muye998** [comment]
Hi, guys, can you tell me how many chips support using QEMU to emulate?

**Comment by igrr** [comment]
Out of Espressif chips, only ESP32 at this point.

**Comment by muye998** [comment]
@igrr Oh,thank you very much! 
I have used the C3 and look for the way to emulate in QEMU for 2 weeks.
Maybe I didn see the support range of chip in the documents, so sad

**Comment by muye998** [comment]
@igrr BTW, whether it is possible to support the C3 or S3 chip in this year?
