### ISSUE TITLE
Building on M1 silicon Mac (QEMU-98)

### ISSUE THREAD

**Issue by pptz** [espressif/qemu#64]
Following the build instructions, my `./configure...` output reads `Host machine cpu family: x86_64`, and compilation fails with an issue related to x86 headers. I have Rosetta 2 installed. A colleague on a similar machine does not experience the issue. Any ideas?

**Comment by igrr** [comment]
What is the output of `arch` command on yours and your colleague's computer?

If you see x86_64 instead of arm64, then the Terminal app might be configured to run in Rosetta. If so, right-click the Terminal app in the Finder, choose Get info and uncheck the "Open using Rosetta" checkbox.

Note that this will affect all other apps you launch via the Terminal.

**Comment by pptz** [comment]
Thanks. Yet we both get `arm64`.

Having said that, I don't have an "open using Rosetta" checkbox in the apps that Finder lists (and Terminal isn't one of those listed either).

**Comment by igrr** [comment]
> and Terminal isn't one of those listed either, though I do of course have it installed

Terminal is typically found under Applications > Utilities.

If you build any of the upstream QEMU releases, do you get the same result as with this fork? Another thing to try might be to compare the `./configure` outputs you and your colleague get line-by-line, perhaps that reveals some difference between your computers. I'm sorry, I don't really know what else to suggest.

**Comment by pptz** [comment]
> Terminal is typically found under Applications > Utilities.
Thanks. "open using Rosetta" is unchecked.

> f you build any of the upstream QEMU releases, do you get the same result as with this fork?
Indeed I do, even as both `arch` and `uname -m` return `arm64`. In the output of `./configure` I see 
```
Host machine cpu family: x86_64
Host machine cpu: x86_64
```
My colleague sees `arm64`, as it should be.

Thanks for the help, this issue can be closed as unrelated to the project.

**Comment by igrr** [comment]
I see, maybe it's that your Python interpreter is an x86_84 one, and is launched in Rosetta?

Could you run `python -c "import platform; print(platform.machine())"` and see if it says `arm64`?

**Comment by pptz** [comment]
> maybe it's that your Python interpreter is an x86_84 one

Astute! Googling around before I read your suggestion led me to a similar thought. I had an `anaconda3` installation that was supplying `python`, and once I uninstalled it, the `./configure` script recognises the correct architecture.

Thanks!
