### ISSUE TITLE
eFuse BLOCK0 MAC (QEMU-135)

### ISSUE THREAD

**Issue by BG7YWL** [espressif/qemu#76]
How to specify the MAC address of eFuse BLOCK0.
The ID I obtained through machine.unique_id() is b'\x00\x00\x00\x00\x00\x00'

**Comment by igrr** [comment]
Could you please clarify what `machine.unique_id()` is? It looks like a function call, but in which language/environment/library?

**Comment by BG7YWL** [comment]
ESP32-D0WD-V3，MicroPython
![Snipaste_2023-06-15_15-43-53](https://github.com/espressif/qemu/assets/9145406/0204acbb-db0a-4a6d-a678-f5e5fb166d50)

**Comment by igrr** [comment]
I see, in this case you need to do the following:

1. Enable eFuse emulation: https://github.com/espressif/qemu/wiki#specifying-efuse-storage
2. Generate eFuse binary, I have put a script here: https://gist.github.com/igrr/3537f8ddb03a50aa980e2e0c121c7581
