### ISSUE TITLE
binary install on ubuntu does not work. (QEMU-185)

### ISSUE THREAD

**Issue by FransM** [espressif/qemu#94]
Not sure if this is an issue for this git, but reporting it anyway.

I tried to install qemu emulator on Ubuntu 22.04 64 bit. as outlined here: https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-guides/tools/qemu.html 

`python $IDF_PATH/tools/idf_tools.py install qemu-xtensa qemu-riscv32`

That installs but when I try to run it I get:
```

frans@laptop:~/git/esp-idf$ idf.py qemu 
The following Python requirements are not satisfied:
Requirement 'pyparsing>=3.1.0' was not met. Installed version: 3.0.9
To install the missing packages, please run "install.sh"
Diagnostic information:
    IDF_PYTHON_ENV_PATH: /home/frans/.espressif/python_env/idf5.3_py3.10_env
    Python interpreter used: /home/frans/.espressif/python_env/idf5.3_py3.10_env/bin/python
Constraint file: /home/frans/.espressif/espidf.constraints.v5.3.txt
Requirement files:
 - /home/frans/git/esp-idf/tools/requirements/requirements.core.txt
```

I reran install.sh but that did not work

And when I try to reinstally pyparsing through pip I get
```
frans@laptop:~/git/esp-idf$ pip install pyparsing
Requirement already satisfied: pyparsing in /home/frans/.espressif/python_env/idf5.3_py3.10_env/lib/python3.10/site-packages (3.0.9)
```

**Comment by igrr** [comment]
It doesn't look like a QEMU-specific issue, you'll probably get the same error for other idf.py commands if the required package is not installed.

Please try installing libslirp and libsdl2.0, and then run install.sh and `. ./export.sh` again, perhaps that is the issue you have encountered: https://github.com/espressif/esp-idf/issues/13152

**Comment by igrr** [comment]
I see, that's interesting! I still don't understand why only one idf.py command was failing, as the python environment check is also done for the rest of the commands. But since you have solved the issue, let's keep it closed. We can investigate if it gets reported again.
